### ISSUE TITLE
Graph-based solution

### ISSUE THREAD

**Issue by bswck** [bswck/configzen-v2#1]
`base.yml`
```yaml
app:
  version: 1.0.0
```
`debug.yml`
```yaml
^extend: base.yml
# application settings
+app:
  debug: true  # disable in production
  # bind locally, 0.0.0.0 binds all interfaces!
  host: 127.0.0.1
  port: 4892
bot:
  owner_ids:
  - 123456789  # bswck
```

![image](https://github.com/bswck/configzen-v2/assets/64036239/a084e393-0124-4a42-899d-2a8ddb3ccbf0)

`config.py`
```py
from ipaddress import IPv4Address
from configzen import BaseConfig

class AppConfig(BaseConfig):
    version: str
    debug: bool
    host: IPv4Address
    port: int

class BotConfig(BaseConfig):
    owner_ids: list[int]
    token: str  # loaded from env

class Config(BaseConfig):
    app: AppConfig
    bot: BotConfig

Config.load("debug.yml")  # magic happens!
```
